Added address reference to CLI output
rojo-rbx/rojo pull request #556
Opened 2022-06-14 12:00 UTC by WatermelonArray

This pull request just fixes the CLI bug on rojo-rbx/rojo#555

Here is a screenshot of the changes on the output
![2022-06-14-130402_1920x1080_scrot](https://user-images.githubusercontent.com/34957838/173572030-12c4d111-74bc-4de4-8a1b-c1ea4838fded.png)

2022-06-14 12:19 UTC, Kampfkarren commented on src/cli/serve.rs
> +        write!(&mut buffer, "http://localhost:")?;
The same loopback check is done to display the address earlier. You would be better off storing the address in a variable that is used for both displays IMO.

2022-06-14 12:45 UTC, WatermelonArray commented
@Kampfkarren Thanks for the feedback, all sorted!

2022-06-14 12:59 UTC, WatermelonArray commented on src/cli/serve.rs
> +    let address_string = if bind_address.is_loopback() {"localhost"} else {stringify!(bind_address)};
Ah, I tried doing that before but my rust linter was saying that .to_string() wasn't a function in the struct.
Turns out my linter is slow and didn't catch up when I was trying to debug it! So I just tried using stringify!() and the problem went away - forgot that stringify!() does not do what I was trying to.

Anyway, sorted!

2022-06-20 01:51 UTC, LPGhatguy requested changes
Hello, thanks for submitting a PR! I just got back from vacation, submitted a little feedback and approved the CI workflows to run.

2022-06-20 01:51 UTC, LPGhatguy commented on src/cli/serve.rs
> +    write!(&mut buffer, "{}/", port)?;
Let's merge these calls together. You can pass multiple arguments into the same format string, something like this should work:

```rust
write!(&mut buffer, "http://{}:{}/", address_string, port)?;
```

2022-06-29 23:04 UTC, merged