Skip confirming patches that only contain a datamodel name change
rojo-rbx/rojo pull request #688
Opened 2023-05-31 00:59 UTC by boatbomber

Closes #672.

Skips the user confirmation if the patch contains only a datamodel name change.

I decided to build generic PatchSet utility functions in case we need to use similar logic in the future, in addition to maintaining clear division of duties. The app code shouldn't be too dependent upon patch internal structure when we can avoid it.

2023-06-02 00:05 UTC, kennethloeffler requested changes
Looking pretty good, a few suggestions:

2023-06-02 22:13 UTC, boatbomber commented on plugin/src/PatchSet.lua
> +		local removedId = if type(idOrInstance) == "string" then idOrInstance else instanceMap.fromInstances[idOrInstance]
I copied this logic from the PatchSet summary function, so I'll update that one as well.

2023-06-04 07:59 UTC, kennethloeffler approved these changes

2023-06-30 18:12 UTC, Dekkonot approved these changes

2023-06-30 18:21 UTC, merged