change gitmodules form ssh to https
rojo-rbx/rojo pull request #696
Opened 2023-06-11 23:49 UTC by Boegie19

Why if you want to use ssh you need todo more setup aka add a ssh key into github while with https you don't have to do the extra work aka makes rojo easier to contribute to.

2023-06-12 20:46 UTC, kennethloeffler approved these changes

2023-06-15 01:04 UTC, boatbomber requested changes
I am pretty sure these urls need to end in `.git`, right? At the very least, that's convention. Like so: `https://github.com/Roblox/roact.git`

2023-06-15 09:46 UTC, Boegie19 commented
They can but they don't have to but if you want me to change it sure

2023-06-16 18:40 UTC, boatbomber approved these changes
LGTM

2023-06-16 18:41 UTC, merged