Make CI only run in PRs that change relevant files
rojo-rbx/rojo pull request #751
Opened 2023-07-28 23:16 UTC by Dekkonot

It only makes sense for us to run CI on pull requests that modify files that might change our builds. We should probably still run it on every commit though, just to be sure.

2023-07-29 00:50 UTC, kennethloeffler requested changes
If we're gonna do this, I think it should include more extensions: 
* `.rbxmx`
* `.rbxm`
* `.rbxlx`
* `.rbxl`
* `.txt`
* `.yml`
* `.csv`

This includes files that could change the results of tests or that could change build results, both now and the in the future.

There's an argument to be made that this list should also have extensions in `assets/` like `.png`, `.mp3`, and `.svg`, but since tmk that directory is currently only used for archival purposes, I chose not to include them.

2023-07-30 20:03 UTC, Dekkonot commented
That's completely fair, I forgot those. It might be more reasonable to just run CI when specific folders change, but that's not really future proof.

2023-08-03 00:56 UTC, boatbomber approved these changes

2023-08-03 00:57 UTC, boatbomber commented
Most PRs are likely going to hit this anyway, but at least markdown-only PRs will be saved.

2023-08-04 06:00 UTC, Dekkonot commented
um?

2023-08-15 12:49 UTC, boatbomber commented
I think that this PR disables that workflow on itself, but GitHub still expects it because it's on master. So it just never runs but is annoyingly still expected. Who has permission level high enough to hit the ignore button and merge anyway?

2023-09-09 06:53 UTC, sasial-dev requested changes

2023-09-09 06:53 UTC, sasial-dev commented on .github/workflows/ci.yml
> +    paths: ["*.rs", "*.toml", "*.json", "*.lua", "*.luau", "*.rbxm", "*.rbxl", "*.rbxmx", "*.rbxlx", "*.txt", "*.yml", "*.csv"]
CI should run when test files have changed:
```suggestion
    paths: ["*.rs", "*.toml", "*.json", "*.lua", "*.luau", "*.rbxm", "*.rbxl", "*.rbxmx", "*.rbxlx", "*.txt", "*.yml", "*.csv", "*.snap"]
```

2023-09-09 07:28 UTC, Dekkonot commented
Given how many file types we actually need this to run for, I'm gonna just close this I think. Not worth it to shave time off of markdown edits!

2023-09-09 07:28 UTC, closed without merging