Update rbx_dom dependencies
rojo-rbx/rojo pull request #768
Opened 2023-08-09 21:06 UTC by Dekkonot

Like it says on the tin, updates the dependencies from rbx_dom.

2023-08-09 21:12 UTC, kennethloeffler requested changes
Make sure to replace rbx_dom_lua as well!

2023-08-09 21:17 UTC, Dekkonot commented
Whoops! That would've been embarassing.

2023-08-09 21:36 UTC, kennethloeffler approved these changes

2023-08-09 21:43 UTC, Dekkonot commented
i hate github

2023-08-10 04:54 UTC, boatbomber approved these changes

2023-08-10 04:54 UTC, merged